### ISSUE TITLE
Prepare 2nd payload for Zenodo

### ISSUE THREAD

**Issue by vukosim** [dsfsi/masakhane-web#69]
#### Description

For the models that are missing in Zenodo but are on Masakhane Web Translate, lets create the zip payloads to be uploaded to Zenodo. Once on Zenodo, the links in available models, should now point to Zenodo
Refactor

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Create the zip payloads to be uploaded to Zenodo.
- [x] links in available models, should now point to Zenodo
- [x] Refactor code to also Support Zenodo based downloads of models
- [x] Commit, pull request

**Comment by Zenthon** [comment]
All that is left is for @vukosim to upload the zips to zenodo and the links to be tested

**Comment by vukosim** [comment]
@Zenthon did you send me the google links for me to download the zips and upload them on zenodo.

**Comment by Zenthon** [comment]
[ig-en-JW300.zip](https://github.com/dsfsi/masakhane-web/files/10182827/ig-en-JW300.zip)

On Zenodo, the zips are saved as src_lang-trg_lang-baseline. However, some of the models in the available_models.tsv have multiple domains (e.g. en-ti-JW300 and en-ti-Autshuymato)

**Comment by vukosim** [comment]
I think src_lang-trg_lang-subarea-baseline is okay. 

So would be ig-en-JW300-baseline.zip

Also note @Zenthon we do not save models in the repo(so that zip file cannot come into the master branch).

**Comment by Zenthon** [comment]
Noted. Thank you prof

**Comment by vukosim** [comment]
@Zenthon I created a google folder for you to put the models in the meantime.
