### ISSUE TITLE
Deploying recent issues to production

### ISSUE THREAD

**Issue by lastrucci01** [dsfsi/masakhane-web#71]
#### Description
The issues #57 & #69 have been resolved in the PR #70 
We need to merge the changes into production & ensure everything works as expected.

#### Tasks
- [x] Review the production branch
- [x] Merge master into prod after approval of #70 
- [x] Run tests and check all is working fine
- [x] ask @Kabongosalomon to deploy on [Masakhane.io](http://masakhane.io/)
