### ISSUE TITLE
Documentation on the Backend system

### ISSUE THREAD

**Issue by lastrucci01** [dsfsi/masakhane-web#72]
#### Description
After learning about the backend of Masakhane Translate, I'd like to document explanations on the details of the system so future developers can get started easier. 

#### Tasks
- [X] Create a doc for explaining project structure and implementation
- [X] Update nested Readme's
- [X] Add more code comments to important files
